// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adspb/ads.proto

package adspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ads struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	BannerUrl            string   `protobuf:"bytes,8,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ads) Reset()         { *m = Ads{} }
func (m *Ads) String() string { return proto.CompactTextString(m) }
func (*Ads) ProtoMessage()    {}
func (*Ads) Descriptor() ([]byte, []int) {
	return fileDescriptor_057a582e76dd329c, []int{0}
}

func (m *Ads) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ads.Unmarshal(m, b)
}
func (m *Ads) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ads.Marshal(b, m, deterministic)
}
func (m *Ads) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ads.Merge(m, src)
}
func (m *Ads) XXX_Size() int {
	return xxx_messageInfo_Ads.Size(m)
}
func (m *Ads) XXX_DiscardUnknown() {
	xxx_messageInfo_Ads.DiscardUnknown(m)
}

var xxx_messageInfo_Ads proto.InternalMessageInfo

func (m *Ads) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ads) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Ads) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Ads) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Ads) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Ads) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Ads) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Ads) GetBannerUrl() string {
	if m != nil {
		return m.BannerUrl
	}
	return ""
}

type CreateAdsRequest struct {
	Ads                  *Ads     `protobuf:"bytes,1,opt,name=ads,proto3" json:"ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdsRequest) Reset()         { *m = CreateAdsRequest{} }
func (m *CreateAdsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAdsRequest) ProtoMessage()    {}
func (*CreateAdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057a582e76dd329c, []int{1}
}

func (m *CreateAdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdsRequest.Unmarshal(m, b)
}
func (m *CreateAdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdsRequest.Marshal(b, m, deterministic)
}
func (m *CreateAdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdsRequest.Merge(m, src)
}
func (m *CreateAdsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAdsRequest.Size(m)
}
func (m *CreateAdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdsRequest proto.InternalMessageInfo

func (m *CreateAdsRequest) GetAds() *Ads {
	if m != nil {
		return m.Ads
	}
	return nil
}

type CreateAdsResponse struct {
	Ads                  *Ads     `protobuf:"bytes,1,opt,name=ads,proto3" json:"ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdsResponse) Reset()         { *m = CreateAdsResponse{} }
func (m *CreateAdsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAdsResponse) ProtoMessage()    {}
func (*CreateAdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057a582e76dd329c, []int{2}
}

func (m *CreateAdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdsResponse.Unmarshal(m, b)
}
func (m *CreateAdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdsResponse.Marshal(b, m, deterministic)
}
func (m *CreateAdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdsResponse.Merge(m, src)
}
func (m *CreateAdsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAdsResponse.Size(m)
}
func (m *CreateAdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdsResponse proto.InternalMessageInfo

func (m *CreateAdsResponse) GetAds() *Ads {
	if m != nil {
		return m.Ads
	}
	return nil
}

func init() {
	proto.RegisterType((*Ads)(nil), "blog.Ads")
	proto.RegisterType((*CreateAdsRequest)(nil), "blog.CreateAdsRequest")
	proto.RegisterType((*CreateAdsResponse)(nil), "blog.CreateAdsResponse")
}

func init() { proto.RegisterFile("adspb/ads.proto", fileDescriptor_057a582e76dd329c) }

var fileDescriptor_057a582e76dd329c = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xf4, 0x30,
	0x10, 0xc6, 0xd9, 0x76, 0xdb, 0xbe, 0x9d, 0x17, 0xfc, 0x13, 0xc4, 0x0d, 0x8a, 0x20, 0x3d, 0x79,
	0xea, 0xca, 0x7a, 0xf5, 0x52, 0x3d, 0xe9, 0x71, 0xc5, 0x8b, 0x97, 0x25, 0xdd, 0x19, 0x34, 0x50,
	0x93, 0x9a, 0x49, 0xfd, 0x82, 0x7e, 0x31, 0x49, 0xa2, 0x22, 0x0a, 0x1e, 0x7f, 0xbf, 0xa7, 0xcf,
	0x34, 0xc3, 0xc0, 0xae, 0x42, 0x1e, 0xfb, 0xa5, 0x42, 0x6e, 0x47, 0x67, 0xbd, 0x15, 0xf3, 0x7e,
	0xb0, 0x8f, 0xcd, 0xdb, 0x0c, 0xf2, 0x0e, 0x59, 0xec, 0x40, 0xa6, 0x51, 0xce, 0x4e, 0x67, 0x67,
	0xf5, 0x3a, 0xd3, 0x28, 0x16, 0x50, 0x4d, 0x4c, 0x6e, 0xa3, 0x51, 0x66, 0x51, 0x96, 0x01, 0x6f,
	0x50, 0x1c, 0x40, 0xe1, 0xb5, 0x1f, 0x48, 0xe6, 0x51, 0x27, 0x10, 0x12, 0xaa, 0xad, 0x35, 0x9e,
	0x8c, 0x97, 0xf3, 0xe8, 0x3f, 0x31, 0x24, 0x0a, 0xd1, 0x11, 0xb3, 0x2c, 0x52, 0xf2, 0x81, 0x61,
	0x12, 0x3d, 0x2b, 0x3d, 0xc8, 0x32, 0x4d, 0x8a, 0x10, 0xec, 0xf8, 0x64, 0x0d, 0xc9, 0x2a, 0xd9,
	0x08, 0xe2, 0x04, 0xa0, 0x57, 0xc6, 0x90, 0xdb, 0x4c, 0x6e, 0x90, 0xff, 0x62, 0x54, 0x27, 0x73,
	0xef, 0x86, 0x66, 0x09, 0x7b, 0xd7, 0x8e, 0x94, 0xa7, 0x0e, 0x79, 0x4d, 0x2f, 0x13, 0xb1, 0x17,
	0xc7, 0x90, 0x2b, 0xe4, 0xb8, 0xd2, 0xff, 0x55, 0xdd, 0x86, 0x6d, 0xdb, 0x10, 0x07, 0xdb, 0x9c,
	0xc3, 0xfe, 0xb7, 0x02, 0x8f, 0xd6, 0x30, 0xfd, 0xd9, 0x58, 0xdd, 0x02, 0x74, 0xc8, 0x77, 0xe4,
	0x5e, 0xf5, 0x96, 0xc4, 0x25, 0xd4, 0x5f, 0x7d, 0x71, 0x98, 0x3e, 0xfd, 0xf9, 0x82, 0xa3, 0xc5,
	0x2f, 0x9f, 0x7e, 0x74, 0x55, 0x3d, 0x14, 0xf1, 0x1a, 0x7d, 0x19, 0x4f, 0x71, 0xf1, 0x1e, 0x00,
	0x00, 0xff, 0xff, 0xdb, 0x02, 0x6b, 0x64, 0x9d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdsServiceClient is the client API for AdsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdsServiceClient interface {
	CreateAds(ctx context.Context, in *CreateAdsRequest, opts ...grpc.CallOption) (*CreateAdsResponse, error)
}

type adsServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdsServiceClient(cc *grpc.ClientConn) AdsServiceClient {
	return &adsServiceClient{cc}
}

func (c *adsServiceClient) CreateAds(ctx context.Context, in *CreateAdsRequest, opts ...grpc.CallOption) (*CreateAdsResponse, error) {
	out := new(CreateAdsResponse)
	err := c.cc.Invoke(ctx, "/blog.AdsService/CreateAds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdsServiceServer is the server API for AdsService service.
type AdsServiceServer interface {
	CreateAds(context.Context, *CreateAdsRequest) (*CreateAdsResponse, error)
}

// UnimplementedAdsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdsServiceServer struct {
}

func (*UnimplementedAdsServiceServer) CreateAds(ctx context.Context, req *CreateAdsRequest) (*CreateAdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAds not implemented")
}

func RegisterAdsServiceServer(s *grpc.Server, srv AdsServiceServer) {
	s.RegisterService(&_AdsService_serviceDesc, srv)
}

func _AdsService_CreateAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).CreateAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.AdsService/CreateAds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).CreateAds(ctx, req.(*CreateAdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.AdsService",
	HandlerType: (*AdsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAds",
			Handler:    _AdsService_CreateAds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adspb/ads.proto",
}
