// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adspb/ads.proto

package adspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ads struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	BannerUrl            string   `protobuf:"bytes,8,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ads) Reset()         { *m = Ads{} }
func (m *Ads) String() string { return proto.CompactTextString(m) }
func (*Ads) ProtoMessage()    {}
func (*Ads) Descriptor() ([]byte, []int) {
	return fileDescriptor_057a582e76dd329c, []int{0}
}

func (m *Ads) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ads.Unmarshal(m, b)
}
func (m *Ads) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ads.Marshal(b, m, deterministic)
}
func (m *Ads) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ads.Merge(m, src)
}
func (m *Ads) XXX_Size() int {
	return xxx_messageInfo_Ads.Size(m)
}
func (m *Ads) XXX_DiscardUnknown() {
	xxx_messageInfo_Ads.DiscardUnknown(m)
}

var xxx_messageInfo_Ads proto.InternalMessageInfo

func (m *Ads) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ads) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Ads) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Ads) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Ads) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Ads) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Ads) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Ads) GetBannerUrl() string {
	if m != nil {
		return m.BannerUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Ads)(nil), "blog.Ads")
}

func init() { proto.RegisterFile("adspb/ads.proto", fileDescriptor_057a582e76dd329c) }

var fileDescriptor_057a582e76dd329c = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0x69, 0xdf, 0x6b, 0x63, 0x07, 0x51, 0x08, 0x82, 0xb3, 0x11, 0xc4, 0x95, 0x2b, 0x05,
	0xfd, 0x82, 0xba, 0x73, 0xab, 0xb8, 0x71, 0x53, 0x92, 0xce, 0xa0, 0x81, 0x98, 0x94, 0x24, 0xf5,
	0x07, 0xfd, 0x31, 0xc9, 0x44, 0x97, 0xe7, 0x1c, 0xb8, 0x70, 0xe1, 0xdc, 0x50, 0xde, 0xec, 0xbd,
	0xa1, 0x7c, 0xb7, 0xa5, 0x58, 0xa2, 0x3e, 0x5a, 0x1f, 0x3f, 0x6e, 0x7e, 0x3a, 0x38, 0xcc, 0x94,
	0xf5, 0x19, 0xf4, 0x8e, 0xb0, 0xbb, 0xee, 0x6e, 0xa7, 0x97, 0xde, 0x91, 0xbe, 0x04, 0xb5, 0x67,
	0x4e, 0x8b, 0x23, 0xec, 0x45, 0x8e, 0x15, 0x9f, 0x49, 0x5f, 0xc0, 0x50, 0x5c, 0xf1, 0x8c, 0x07,
	0xd1, 0x0d, 0x34, 0x82, 0x5a, 0x63, 0x28, 0x1c, 0x0a, 0x1e, 0xc5, 0xff, 0x63, 0x2d, 0x86, 0x28,
	0x71, 0xce, 0x38, 0xb4, 0xf2, 0x87, 0x75, 0x89, 0xbf, 0x8c, 0xf3, 0x38, 0xb6, 0x25, 0x81, 0x6a,
	0xb7, 0xcf, 0x18, 0x18, 0x55, 0xb3, 0x02, 0xfa, 0x0a, 0xc0, 0x9a, 0x10, 0x38, 0x2d, 0x7b, 0xf2,
	0x78, 0x22, 0x69, 0x6a, 0xe6, 0x2d, 0xf9, 0x87, 0x53, 0x80, 0x99, 0xf2, 0x2b, 0xa7, 0x6f, 0xb7,
	0xf2, 0x93, 0x7a, 0x1f, 0xe4, 0xac, 0x1d, 0xe5, 0xe9, 0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x72, 0xad, 0xa4, 0x14, 0xfc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdsServiceClient is the client API for AdsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdsServiceClient interface {
}

type adsServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdsServiceClient(cc *grpc.ClientConn) AdsServiceClient {
	return &adsServiceClient{cc}
}

// AdsServiceServer is the server API for AdsService service.
type AdsServiceServer interface {
}

// UnimplementedAdsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdsServiceServer struct {
}

func RegisterAdsServiceServer(s *grpc.Server, srv AdsServiceServer) {
	s.RegisterService(&_AdsService_serviceDesc, srv)
}

var _AdsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.AdsService",
	HandlerType: (*AdsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "adspb/ads.proto",
}
