// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adspb/ads.proto

package adspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ads struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	BannerUrl            string   `protobuf:"bytes,8,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ads) Reset()         { *m = Ads{} }
func (m *Ads) String() string { return proto.CompactTextString(m) }
func (*Ads) ProtoMessage()    {}
func (*Ads) Descriptor() ([]byte, []int) {
	return fileDescriptor_057a582e76dd329c, []int{0}
}

func (m *Ads) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ads.Unmarshal(m, b)
}
func (m *Ads) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ads.Marshal(b, m, deterministic)
}
func (m *Ads) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ads.Merge(m, src)
}
func (m *Ads) XXX_Size() int {
	return xxx_messageInfo_Ads.Size(m)
}
func (m *Ads) XXX_DiscardUnknown() {
	xxx_messageInfo_Ads.DiscardUnknown(m)
}

var xxx_messageInfo_Ads proto.InternalMessageInfo

func (m *Ads) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ads) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Ads) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Ads) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Ads) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Ads) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Ads) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Ads) GetBannerUrl() string {
	if m != nil {
		return m.BannerUrl
	}
	return ""
}

type CreateAdsRequest struct {
	Ads                  *Ads     `protobuf:"bytes,1,opt,name=ads,proto3" json:"ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdsRequest) Reset()         { *m = CreateAdsRequest{} }
func (m *CreateAdsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAdsRequest) ProtoMessage()    {}
func (*CreateAdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057a582e76dd329c, []int{1}
}

func (m *CreateAdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdsRequest.Unmarshal(m, b)
}
func (m *CreateAdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdsRequest.Marshal(b, m, deterministic)
}
func (m *CreateAdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdsRequest.Merge(m, src)
}
func (m *CreateAdsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAdsRequest.Size(m)
}
func (m *CreateAdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdsRequest proto.InternalMessageInfo

func (m *CreateAdsRequest) GetAds() *Ads {
	if m != nil {
		return m.Ads
	}
	return nil
}

type CreateAdsResponse struct {
	Ads                  *Ads     `protobuf:"bytes,1,opt,name=ads,proto3" json:"ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdsResponse) Reset()         { *m = CreateAdsResponse{} }
func (m *CreateAdsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAdsResponse) ProtoMessage()    {}
func (*CreateAdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057a582e76dd329c, []int{2}
}

func (m *CreateAdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdsResponse.Unmarshal(m, b)
}
func (m *CreateAdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdsResponse.Marshal(b, m, deterministic)
}
func (m *CreateAdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdsResponse.Merge(m, src)
}
func (m *CreateAdsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAdsResponse.Size(m)
}
func (m *CreateAdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdsResponse proto.InternalMessageInfo

func (m *CreateAdsResponse) GetAds() *Ads {
	if m != nil {
		return m.Ads
	}
	return nil
}

type ReadAdsRequest struct {
	AdsId                string   `protobuf:"bytes,1,opt,name=ads_id,json=adsId,proto3" json:"ads_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAdsRequest) Reset()         { *m = ReadAdsRequest{} }
func (m *ReadAdsRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAdsRequest) ProtoMessage()    {}
func (*ReadAdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057a582e76dd329c, []int{3}
}

func (m *ReadAdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAdsRequest.Unmarshal(m, b)
}
func (m *ReadAdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAdsRequest.Marshal(b, m, deterministic)
}
func (m *ReadAdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAdsRequest.Merge(m, src)
}
func (m *ReadAdsRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAdsRequest.Size(m)
}
func (m *ReadAdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAdsRequest proto.InternalMessageInfo

func (m *ReadAdsRequest) GetAdsId() string {
	if m != nil {
		return m.AdsId
	}
	return ""
}

type ReadAdsResponse struct {
	Ads                  *Ads     `protobuf:"bytes,1,opt,name=ads,proto3" json:"ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAdsResponse) Reset()         { *m = ReadAdsResponse{} }
func (m *ReadAdsResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAdsResponse) ProtoMessage()    {}
func (*ReadAdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057a582e76dd329c, []int{4}
}

func (m *ReadAdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAdsResponse.Unmarshal(m, b)
}
func (m *ReadAdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAdsResponse.Marshal(b, m, deterministic)
}
func (m *ReadAdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAdsResponse.Merge(m, src)
}
func (m *ReadAdsResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAdsResponse.Size(m)
}
func (m *ReadAdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAdsResponse proto.InternalMessageInfo

func (m *ReadAdsResponse) GetAds() *Ads {
	if m != nil {
		return m.Ads
	}
	return nil
}

func init() {
	proto.RegisterType((*Ads)(nil), "ads.Ads")
	proto.RegisterType((*CreateAdsRequest)(nil), "ads.CreateAdsRequest")
	proto.RegisterType((*CreateAdsResponse)(nil), "ads.CreateAdsResponse")
	proto.RegisterType((*ReadAdsRequest)(nil), "ads.ReadAdsRequest")
	proto.RegisterType((*ReadAdsResponse)(nil), "ads.ReadAdsResponse")
}

func init() { proto.RegisterFile("adspb/ads.proto", fileDescriptor_057a582e76dd329c) }

var fileDescriptor_057a582e76dd329c = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x4f, 0x02, 0x31,
	0x10, 0x85, 0x03, 0xb8, 0xbb, 0x30, 0x26, 0xa0, 0x15, 0xb4, 0x21, 0x31, 0x31, 0x5c, 0xf4, 0x22,
	0x24, 0xe8, 0xc9, 0x1b, 0x7a, 0xe2, 0x8a, 0xf1, 0xe2, 0x85, 0x14, 0x66, 0x12, 0x37, 0x59, 0xbb,
	0x6b, 0xa7, 0x78, 0xf4, 0xcf, 0xf9, 0xc7, 0x4c, 0xa7, 0xb8, 0x01, 0x0e, 0x7a, 0x7c, 0xdf, 0xbc,
	0xbe, 0xf6, 0x35, 0x03, 0x3d, 0x83, 0x5c, 0xad, 0x26, 0x06, 0x79, 0x5c, 0xb9, 0xd2, 0x97, 0xaa,
	0x65, 0x90, 0x47, 0xdf, 0x0d, 0x68, 0xcd, 0x90, 0x55, 0x17, 0x9a, 0x39, 0xea, 0xc6, 0x55, 0xe3,
	0xa6, 0xb3, 0x68, 0xe6, 0xa8, 0x2e, 0x20, 0xdb, 0x30, 0xb9, 0x65, 0x8e, 0xba, 0x29, 0x30, 0x0d,
	0x72, 0x8e, 0xaa, 0x0f, 0x89, 0xcf, 0x7d, 0x41, 0xba, 0x25, 0x38, 0x0a, 0xa5, 0x21, 0x5b, 0x97,
	0xd6, 0x93, 0xf5, 0xfa, 0x48, 0xf8, 0xaf, 0x0c, 0x13, 0x83, 0xe8, 0x88, 0x59, 0x27, 0x71, 0xb2,
	0x95, 0x21, 0x89, 0xde, 0x4d, 0x5e, 0xe8, 0x34, 0x26, 0x89, 0x08, 0xb4, 0x7a, 0x2b, 0x2d, 0xe9,
	0x2c, 0x52, 0x11, 0xea, 0x12, 0x60, 0x65, 0xac, 0x25, 0xb7, 0xdc, 0xb8, 0x42, 0xb7, 0x65, 0xd4,
	0x89, 0xe4, 0xc5, 0x15, 0xa3, 0x31, 0x9c, 0x3c, 0x39, 0x32, 0x9e, 0x66, 0xc8, 0x0b, 0xfa, 0xd8,
	0x10, 0x7b, 0x35, 0x84, 0x50, 0x50, 0x2a, 0x1d, 0x4f, 0xdb, 0xe3, 0xd0, 0x3b, 0x4c, 0xa5, 0xf5,
	0x04, 0x4e, 0x77, 0xfc, 0x5c, 0x95, 0x96, 0xe9, 0xcf, 0x03, 0xd7, 0xd0, 0x5d, 0x90, 0xc1, 0x9d,
	0xf8, 0x01, 0xa4, 0x06, 0x79, 0x59, 0x7f, 0x5a, 0x62, 0x90, 0xe7, 0x38, 0xba, 0x85, 0x5e, 0x6d,
	0xfc, 0x3f, 0x77, 0xfa, 0x05, 0x30, 0x43, 0x7e, 0x26, 0xf7, 0x99, 0xaf, 0x49, 0x3d, 0x40, 0xa7,
	0x7e, 0x96, 0x1a, 0x88, 0xf3, 0xb0, 0xd6, 0xf0, 0xfc, 0x10, 0x6f, 0x6f, 0xb9, 0x87, 0x6c, 0x7b,
	0xb1, 0x3a, 0x13, 0xcb, 0xfe, 0x7b, 0x87, 0xfd, 0x7d, 0x18, 0x4f, 0x3d, 0x66, 0xaf, 0x89, 0xac,
	0xc5, 0x2a, 0x95, 0x9d, 0xb8, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x0c, 0x71, 0xe1, 0x26,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdsServiceClient is the client API for AdsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdsServiceClient interface {
	CreateAds(ctx context.Context, in *CreateAdsRequest, opts ...grpc.CallOption) (*CreateAdsResponse, error)
	ReadAds(ctx context.Context, in *ReadAdsRequest, opts ...grpc.CallOption) (*ReadAdsResponse, error)
}

type adsServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdsServiceClient(cc *grpc.ClientConn) AdsServiceClient {
	return &adsServiceClient{cc}
}

func (c *adsServiceClient) CreateAds(ctx context.Context, in *CreateAdsRequest, opts ...grpc.CallOption) (*CreateAdsResponse, error) {
	out := new(CreateAdsResponse)
	err := c.cc.Invoke(ctx, "/ads.AdsService/CreateAds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) ReadAds(ctx context.Context, in *ReadAdsRequest, opts ...grpc.CallOption) (*ReadAdsResponse, error) {
	out := new(ReadAdsResponse)
	err := c.cc.Invoke(ctx, "/ads.AdsService/ReadAds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdsServiceServer is the server API for AdsService service.
type AdsServiceServer interface {
	CreateAds(context.Context, *CreateAdsRequest) (*CreateAdsResponse, error)
	ReadAds(context.Context, *ReadAdsRequest) (*ReadAdsResponse, error)
}

// UnimplementedAdsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdsServiceServer struct {
}

func (*UnimplementedAdsServiceServer) CreateAds(ctx context.Context, req *CreateAdsRequest) (*CreateAdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAds not implemented")
}
func (*UnimplementedAdsServiceServer) ReadAds(ctx context.Context, req *ReadAdsRequest) (*ReadAdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAds not implemented")
}

func RegisterAdsServiceServer(s *grpc.Server, srv AdsServiceServer) {
	s.RegisterService(&_AdsService_serviceDesc, srv)
}

func _AdsService_CreateAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).CreateAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/CreateAds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).CreateAds(ctx, req.(*CreateAdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_ReadAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).ReadAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ads.AdsService/ReadAds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).ReadAds(ctx, req.(*ReadAdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ads.AdsService",
	HandlerType: (*AdsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAds",
			Handler:    _AdsService_CreateAds_Handler,
		},
		{
			MethodName: "ReadAds",
			Handler:    _AdsService_ReadAds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adspb/ads.proto",
}
